
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package minipascal.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_DER = 25;
  public static final int DOSPUNTOS = 29;
  public static final int CONST = 10;
  public static final int CHAR = 4;
  public static final int NUM_INTEGER = 36;
  public static final int CONSTBOOL = 20;
  public static final int INTEGER = 2;
  public static final int REPEAT = 18;
  public static final int PUNTOCOMA = 28;
  public static final int FOR = 16;
  public static final int IDENTIFICADOR = 34;
  public static final int FUNC_WRITE = 22;
  public static final int RECORD = 5;
  public static final int BEGIN = 12;
  public static final int UNTIL = 19;
  public static final int OP_BOOLEANO = 31;
  public static final int IF = 7;
  public static final int OP_RELACIONAL = 30;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int error = 1;
  public static final int PROGRAM = 6;
  public static final int COMA = 26;
  public static final int OP_MULT = 33;
  public static final int CONSTSTR = 38;
  public static final int PAR_IZQ = 24;
  public static final int ASIGNACION = 23;
  public static final int ELSE = 9;
  public static final int PUNTO = 27;
  public static final int TO = 17;
  public static final int WHILE = 14;
  public static final int THEN = 8;
  public static final int END = 13;
  public static final int CONSTCHAR = 37;
  public static final int OP_SUMA = 32;
  public static final int NUM_FLOAT = 35;
  public static final int VAR = 11;
  public static final int DO = 15;
  public static final int FUNC_READ = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "BOOLEAN",
  "CHAR",
  "RECORD",
  "PROGRAM",
  "IF",
  "THEN",
  "ELSE",
  "CONST",
  "VAR",
  "BEGIN",
  "END",
  "WHILE",
  "DO",
  "FOR",
  "TO",
  "REPEAT",
  "UNTIL",
  "CONSTBOOL",
  "FUNC_READ",
  "FUNC_WRITE",
  "ASIGNACION",
  "PAR_IZQ",
  "PAR_DER",
  "COMA",
  "PUNTO",
  "PUNTOCOMA",
  "DOSPUNTOS",
  "OP_RELACIONAL",
  "OP_BOOLEANO",
  "OP_SUMA",
  "OP_MULT",
  "IDENTIFICADOR",
  "NUM_FLOAT",
  "NUM_INTEGER",
  "CONSTCHAR",
  "CONSTSTR"
  };
}

